export const CLAIM_PROCESS = {
    CONNECT_WALLET: "CONNECT_WALLET",
    CONNECT_WALLET_LOADING: "CONNECT_WALLET_LOADING",
}

export const HEXAGON_WIDTH = 12.5;
export const HEXAGON_HEIGHT = 12.3;

export const HEXGRID_RENDER_TOTAL_WIDTH = 90;
export const HEXGRID_RENDER_TOTAL_HEIGHT = 84;
